### PR TITLE
Remove extQueue, modify controller extension

### LINKED ISSUE #52: Traj prediction stores prev altitude w/ wrong type
`prev_alt` is currently a `uint16_t`, but is intended to store a `int32_t` value. This needs to be changed, along with setting the intial value to something more sensible (I'm thinking INT_MAX)

### LINKED ISSUE #71: Modify trajectory prediction to use constant 50% extension area
Don't worry yourself about why, this comes from a discussion I had with Zach. This also means we can descope extension queue
Also, the controller should be modified so the 0 point is 50% extension, rather than 0. This means from the controller perspective we can both "add" and "subtract" drag force, which makes the control problem more friendly

### PR DESCRIPTION
**Pull request by Joe-Joe-Joe-Joe**
Probably warrants testing
closes #71 
closes #52

### CODE REVIEW

**Comment by Armaan-Sengupta** [comment]
Basis of 50% makes sense, I never considered that we could put ourselves into a undershoot even at 0% extension state, good point. Does this also mean then we are reporting apogee to competition using OR simulated  at 50% extension?

File: STM32Cube/Tasks/trajectory.c [hunk 1]
```diff
@@ -269,17 +269,16 @@ Otits_Result_t test_apogeeQueue() {
...
     float prev_time = -1;
-    uint16_t prev_alt = 0xFFFF;
+    int32_t prev_alt = INT_MAX;
     
     for(;;)
     {
         AltTime altTime;
         FusionEuler angles;
-        float ext;
+        const float ext = 0.5;
```
Comment (Armaan-Sengupta) [inline STM32Cube/Tasks/trajectory.c:278]: how does this variable get updated?

**Review by Armaan-Sengupta — APPROVED** [review]
